version: '3.5'

services:
  db:
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:16.2-bookworm
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
